[workspace]
members = [
    "src/program",
]

[package]
name = "digital-marketplace"
version = "0.1.0"
edition = "2021"

[dependencies]
digital-marketplace-program = { path = "src/program" }

[[bin]]
name = "digital-marketplace"
path = "src/main.rs"