[package]
name = "digital-marketplace-program"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bitcoin = "0.30.0"
borsh = "0.10.0"

[lib]
name = "digital_marketplace_program"
path = "src/lib.rs"

[[bin]]
name = "digital-marketplace-program"
path = "src/main.rs"